### ISSUE TITLE
[Question] Network.Wai.getRequestBodyChunk vs Network.Wai.{strict,lazy}RequestBody

### ISSUE THREAD

**Issue by derrickbeining** [digitallyinduced/ihp#757] opened 2021-02-14 17:02 UTC
In [ControllerSupport.hs](https://github.com/digitallyinduced/ihp/blob/3efd155ebc8907eddd41c579d2d61b861c1d733d/IHP/ControllerSupport.hs#L143), IHP is using `Network.Wai.getRequestBodyChunk` to access the request body to store it on the `RequestContext`. Is that the right function to use though? According to the docs, it's design for streaming the payload:

> Get the next chunk of the body. Returns empty when the body is fully consumed.

But IHP only appears to read a single chunk and doesn't check if the body was fully consumed. It seems like `Network.Wai. strictRequestBody` or `Network.Wai.lazyRequestBody` would be the correct choice. Or is there something special going on somewhere that is making `getRequestBodyChunk` read the whole payload? I imagine if `getRequestBodyChunk` wasn't loading the whole payload, someone would have noticed by now, so I perhaps I'm just misunderstanding something.

**Comment by mpscholten** [comment] 2021-02-15 07:46
Agree, we should change it to `strictRequestBody` or `lazyRequestBody` 👍 

I think it currently works because nearly all requests are non chunked.

**Comment by derrickbeining** [comment] 2021-02-15 17:49
@mpscholten would it make sense for IHP to also expose the body as some sort of streaming data type like from `conduit` or `pipe`? It seems like it would be good to give devs the option to stream payloads when it makes sense to do so.

**Comment by mpscholten** [comment] 2021-02-15 18:50
Been thinking about this as well. Likely not possible for now without changing a lot of the internals. The problem is that when we create a new `RequestContext`, the request body will already be consumed. This happens even before routing has happend, so we cannot easily control this on a per-action case.

Maybe we can fix this in IHP v2. Until then the workaround might be to write a custom WAI middleware that is executed outside of the normal IHP control flow.

**Comment by mpscholten** [comment] 2021-02-23 06:38
Just pushed a fix switching to `lazyRequestBody` to master 👍

**Closed** 2021-02-23 06:37 UTC
Labels: enhancement
