### ISSUE TITLE
Running empty test twice fails

### ISSUE THREAD

**Issue by zacwood9** [digitallyinduced/ihp#1318] opened 2022-01-15 19:16 UTC
Given an empty Spec test:

```haskell
testImportListing = aroundAll (withIHPApp WebApplication config) do
  describe "import listing" $ do
    it "adds new listing" $ withContext do
      True `shouldBe` True
```

the test succeeds on the first run, but fails on subsequent runs with

```
IHP> hspec testImportListing

import listing
  adds new listing FAILED [1]
afterAll-hook
  # PENDING: exception in beforeAll-hook (see previous failure)

Failures:

  Test/ImportListings.hs:67:5:
  1) import listing adds new listing
       uncaught exception: IOException of type ResourceBusy
       openFile: resource busy (file is locked)

  To rerun use: --match "/import listing/adds new listing/"

Randomized with seed 2042713658

Finished in 0.0026 seconds
2 examples, 1 failure, 1 pending
*** Exception: ExitFailure 1
```

**Comment by amitaibu** [comment] 2022-01-15 19:20
I see you run the tests with `hspec`, but according to https://ihp.digitallyinduced.com/Guide/testing.html#setup it should be executed differently. Does it also fail with executing from ghci?

**Comment by zacwood9** [comment] 2022-01-15 19:27
I am running the tests from within ghci, in the output I posted I call `hspec` from ghci with the given Spec. I believe this is how the docs execute them as well, just without the wrapper in "main"

**Comment by zacwood9** [comment] 2022-01-15 19:45
Issue was reported on the fourm: https://ihp.digitallyinduced.com/community/ShowThread?threadId=349f909a-4b99-4448-b5f9-cfaefbca9aea, I am investigating now

**Comment by mpscholten** [comment] 2022-01-16 09:24
I cannot reproduce the issue on a different project. I think the issue could be that the log file handle is not closed as expected.

**Comment by mpscholten** [comment] 2022-01-16 09:30
When you replace `config` with `pure ()` you will not get that error anymore.

So try this:
```
testImportListing = aroundAll (withIHPApp WebApplication (pure ())) do
  describe "import listing" $ do
    it "adds new listing" $ withContext do
      True `shouldBe` True
```

This makes it even more likely that it's something in Config that's leaking.

**Comment by mpscholten** [comment] 2022-01-16 09:47
Turned out that the tests didn't call the cleanup handler of the logger (`frameworkConfig |> get #logger |> get #cleanup`) after completion. Therefore the log file handle was not closed. I've pushed a fix 👍

**Closed** 2022-01-16 10:12 UTC
