### ISSUE TITLE
HSX incorrectly removes HTML data attributes with a False value

### ISSUE THREAD

**Issue by nghamilton** [digitallyinduced/ihp#741] opened 2021-02-04 03:38 UTC
HSX removes boolean values when parsing HTML attributes (https://ihp.digitallyinduced.com/Guide/hsx.html#boolean-attribute-values). This leads to unexpected behaviour when setting HTML data attribute values to "false": the data-attribute is not included in the tag.

This fails to include `data-example` in the `div` tag:
```
[hsx| <div data-example={False}></div> |]
```

But this works as expected:
```
[hsx| <div data-example={"false"::Text}></div> |]
```

The documentation should be updated to reflect this or the HSX parsing should operate differently for data attributes?

**Comment by mpscholten** [comment] 2021-02-04 07:47
Here we mainly try to follow the conventions of the HTML standard as described in https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes

> The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.

What is the specific usecase where this behavior is causing you trouble?

**Comment by fegu** [comment] 2021-02-04 20:23
I believe one of the first bugs I fixed in the IDE had this as the root cause so it should at least be documented.

**Comment by nghamilton** [comment] 2021-02-04 21:33
I appreciate how HSX parses to clean and conformant HTML, however the boolean-attributes reference that @mpscholten specified above does not mention data attributes, which are what I am referring to.

If you have a look at https://www.w3.org/TR/html51/dom.html#embedding-custom-non-visible-data-with-the-data-attributes there is no mention of special handling of data attributes that contain boolean values. I believe the correct interpretation of the spec is that the value in the data attribute should be parsed as a string. Here is some more indication that this is the case: https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/dataset#setting_values

A good example of incorrect behaviour: `data-turbolinks={False}` will fail to create a data attribute that disables turbolinks for an element.

**Closed** 2021-04-12 06:00 UTC
