### ISSUE TITLE
SSC Accept nullary types

### ISSUE THREAD

**Issue by s0kil** [digitallyinduced/ihp#1776] opened 2023-07-27 04:48 UTC
With:

```
data PolicyEditorController
    = OpenModalAction
    | CloseModalAction
    deriving (Data, Eq, Show)
```

Calling `OpenModalAction` will fail with:
```
Error in $: When parsing Web.Component.PolicyEditor.PolicyEditorController expected String but got Object.
Error in $: When parsing Web.Component.PolicyEditor.PolicyEditorController expected String but got Object.
Error in $: When parsing Web.Component.PolicyEditor.PolicyEditorController expected String but got Object.
```

**Comment by mpscholten** [comment] 2023-07-27 06:29
Duplicate of https://github.com/digitallyinduced/ihp/issues/923

**Closed** 2023-07-27 20:43 UTC
Labels: bug
