### ISSUE TITLE
Missing fields in generated Edit.hs and New.hs views

### ISSUE THREAD

**Issue by themmes** [digitallyinduced/ihp#194] opened 2020-06-30 05:52 UTC
Hi, I was trying to experiment with a many-to-many relation, but something is wrong in the view generations of the connecting table. See schema below.

## Steps to reproduce

1. ihp-new test
2. cd test and ./start
3. recreate schema in IHP
4. update and push to db
5. create new codegen/Controller for `ProjectProducts`
6. open `http://localhost:8000/NewProjectProduct`

## Expected

A form with two UUID fields and a quantity field

## Bug

The form turns out empty, also in the controller the build statement seems empty.
```
buildProjectProduct projectProduct = projectProduct
    |> fill @'[]
```
I verified that generally when I add an `Int` column to a model it works fine, it almost seems as if the double foreign key is breaking this.

```
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE products (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    project_id UUID NOT NULL
);
CREATE TABLE projects (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
CREATE TABLE project_products (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    project_id UUID NOT NULL,
    product_id UUID NOT NULL,
    quantity INT NOT NULL
);
ALTER TABLE products ADD CONSTRAINT products_ref_project_id FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE NO ACTION;
ALTER TABLE project_products ADD CONSTRAINT project_products_ref_project_id FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE NO ACTION;
ALTER TABLE project_products ADD CONSTRAINT project_products_ref_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE NO ACTION;
```

**Comment by mpscholten** [comment] 2020-07-01 05:25
Hey Tom, thanks :) I'll look into this as soon as possible.

**Comment by mpscholten** [comment] 2020-07-15 06:44
I just reproduced the bug and found the issue. The code gen could not find the table which belongs to the controller (in that case it just falls back to an empty list, because sometimes you want to generate a controller which does not belong to a database table directly).

This is fixed once https://github.com/digitallyinduced/ihp/pull/234 is merged :)

**Closed** 2020-07-15 08:04 UTC

**Comment by themmes** [comment] 2020-08-08 11:03
I just retried this process, but I am actually having the same issue for the same schema as listed above.. Am I doing something wrong? This fix is in the latest release right?

**Comment by mpscholten** [comment] 2020-08-08 11:11
I've just tried to reproduce this again but the generated code looks right. Here's a part of the generated `ProjectProducts.hs`:

```haskell
buildProjectProduct projectProduct = projectProduct
    |> fill @["projectId","productId","quantity"]
```

This looks right. Or am I getting the bug description wrong? :) 

Can you quickly take a look at your `default.nix` and check what `rev` (line 4) is used? Maybe the project is still somehow using an older version

**Comment by themmes** [comment] 2020-08-08 11:16
Ah I understand the confusion, yes that part is there! However, in the View/ProjectProducts/New.hs and Edit.hs

```
renderForm projectProduct = formFor projectProduct [hsx|

    {submitButton}
```

is empty!

**Comment by mpscholten** [comment] 2020-08-08 11:38
Thanks, got it :) Will be fixed via https://github.com/digitallyinduced/ihp/pull/311 It's basically the fix we applied to the controller generator. We somehow missed to apply this to the view gen as well 👍 Tested it locally already and there it's working with the above example.

cc @Laobiz: maybe we can a test case to cover this bug on monday.
