### ISSUE TITLE
generated fromField instance wrong for Enum containing some characters

### ISSUE THREAD

**Issue by VictorElHajj** [digitallyinduced/ihp#327] opened 2020-08-12 21:14 UTC
I have an enum with one possible value being "Tillgänglig"
The generated code for instanceFromField is 
`    fromField field (Just "Tillg\228nglig") = pure Tillgänglig`
However entering it in a form and submitting it is stored as 
`"Tillg\195\164nglig"`

If I change the fromField instance to that it works as expected. However changing the InputValue instance to that instead displays "TillgÃ¤nglig".

It appears there is some inconsistent encoding.

I think it's caused by 
https://github.com/digitallyinduced/ihp/blob/d31e931597c31c8929c4dc1798c5d58c0c817e11/IHP/SchemaCompiler.hs#L281
using "tshow" https://github.com/digitallyinduced/ihp/blob/1b47825984b360913470c7e889a6a49e571e2074/IHP/Prelude.hs#L69 which uses "show" and escapes all non-ascii characters.

**Comment by mpscholten** [comment] 2020-08-24 17:19
Just pushed a fix for this. The issue is caused by "misuse" of inline ByteStrings here. Fixed this by using a Text value and then manually decoding it to a ByteString.

Can you confirm that the issue is fixed? You can update to the fix-commit by following the steps described here: https://ihp.digitallyinduced.com/Guide/updating.html#updating-to-a-specific-git-commit

**Closed** 2020-08-27 07:53 UTC
Labels: bug

**Comment by VictorElHajj** [comment] 2020-08-27 08:26
Sorry for not confirming! Been busy at work. Really glad to see it fixed though 😄
