### ISSUE TITLE
Text and Int types in custom sqlQuery not working

### ISSUE THREAD

**Issue by kodeFant** [digitallyinduced/ihp#428] opened 2020-09-30 20:08 UTC
Hi. I tried to follow the instructions on the docs about custom queries. 

I was wanting to fetch a `count` of the products, but tried the `randomString` example to double check and it did not work either.

The `recentProducts` one works fine by the way.

```haskell
module Web.Controller.FrontPage where

import Web.Controller.Prelude
import Web.View.FrontPage.Index


instance Controller FrontPageController where
    action IndexAction = do
        recentProducts <- sqlQuery "SELECT * FROM products LIMIT 4" ()
        count :: Int  <- sqlQuery "SELECT COUNT(*) FROM products" ()
        randomString :: Text <- sqlQuery "SELECT md5(random()::text)" []
        render IndexView { .. }

```

Error output
```
Web/Controller/FrontPage.hs:10:9: error:
    • Couldn't match expected type ‘[r0]’ with actual type ‘Int’
    • When checking that the pattern signature: Int
        fits the type of its context: [r0]
      In the pattern: count :: Int
      In a stmt of a 'do' block:
        count :: Int <- sqlQuery "SELECT COUNT(*) FROM products" ()
Failed, 35 modules loaded.
   |
10 |         count :: Int  <- sqlQuery "SELECT COUNT(*) FROM products" ()
   |         ^^^^^^^^^^^^

Web/Controller/FrontPage.hs:11:9: error:
    • Couldn't match expected type ‘[r1]’ with actual type ‘Text’
    • When checking that the pattern signature: Text
        fits the type of its context: [r1]
      In the pattern: randomString :: Text
      In a stmt of a 'do' block:
        randomString :: Text <- sqlQuery "SELECT md5(random()::text)" []
   |
11 |         randomString :: Text <- sqlQuery "SELECT md5(random()::text)" []
   |         ^^^^^^^^^^^^^^^^^^^^

```

**Comment by mpscholten** [comment] 2020-10-01 05:27
Thanks for pointing out. Currently the `sqlQuery` function always expects to return a list of rows. So even when there is only a single result, currently it's wrapped inside a list. Also the row itself is expected to be a tuple or wrapped inside `Only`. 

Here's how the code could work:

```
module Web.Controller.FrontPage where

import Web.Controller.Prelude
import Web.View.FrontPage.Index


instance Controller FrontPageController where
    action IndexAction = do
        recentProducts <- sqlQuery "SELECT * FROM products LIMIT 4" ()
        [Only (count :: Int)]  <- sqlQuery "SELECT COUNT(*) FROM products" ()
        [Only (randomString :: Text)] <- sqlQuery "SELECT md5(random()::text)" []
        render IndexView { .. }
```

The same result of the custom queries can also be archived with this:

```
module Web.Controller.FrontPage where

import Web.Controller.Prelude
import Web.View.FrontPage.Index


instance Controller FrontPageController where
    action IndexAction = do
        recentProducts <- sqlQuery "SELECT * FROM products LIMIT 4" ()
        count  <- query @Product |> fetchCount
        randomString <- generateAuthenticationToken
        render IndexView { .. }
```

We should do this to improve:
- Documentation for `fetchCount`
- Add Recipe on `How to generate a random string`
- Add `limit` to query builder (technical it's there already, just has not been exposed via the API)
- Improve documentation on using `sqlQuery` with a single result. Maybe add something like `sqlQuerySingleResult` that automatically unwraps the list and `Only`.

**Comment by mpscholten** [comment] 2020-10-01 15:21
Fixed via:

https://github.com/digitallyinduced/ihp/commit/a741d6eb1bfab866363874f20884a54b38c8e642
https://github.com/digitallyinduced/ihp/commit/f1551704f526c63393be17ba91f0e6a8073cdece
https://github.com/digitallyinduced/ihp/pull/434
https://github.com/digitallyinduced/ihp/commit/e295a216515474a946d4b101e2a332e3ee9fc074

**Comment by mpscholten** [comment] 2020-10-03 06:14
Closing this as I think the issue is fixed with the latest release :) Let me know in case you think otherwise

**Closed by mpscholten** 2020-10-03 06:14 UTC
