### ISSUE TITLE
Creating a `nullable` `TEXT` column in the schema editor causes a failure

### ISSUE THREAD

**Issue by nghamilton** [digitallyinduced/ihp#175] opened 2020-06-28 02:09 UTC
Creating a `nullable` `TEXT` column in the schema editor causes a failure:

```
toDefaultValueExpr: TEXT column needs to have a TextExpression as default value. Got: VarExpression "NULL"
CallStack (from HasCallStack):
  error, called at ./IHP/SchemaCompiler.hs:429:57 in main:IHP.SchemaCompiler
```

```
CREATE TABLE NullFails (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    nullable_field_test TEXT DEFAULT NULL
);
```

Restarting the build script appears to resolve the problem.

**Comment by mpscholten** [comment] 2020-06-28 06:38
Hey, thanks for reporting! 👍 Just found the bug and fixed it via https://github.com/digitallyinduced/ihp/issues/175 The issue is that the SchemaCompiler only accepts lowercase `null` as the null value. With #175 the value `NULL` is also accepted :)

You can work around this issue by just writing `null` in your sql until this is merged. Alternatively you can also update to the latest master version of IHP once the PR is merged.

**Closed** 2020-06-28 07:57 UTC
