### ISSUE TITLE
tuple concurrently updated

### ISSUE THREAD

**Issue by kodeFant** [digitallyinduced/ihp#1543] opened 2022-10-04 08:28 UTC
Hi!

Sometimes I get the error `tuple concurrently updated` error seemingly at random with IHP requests.

Just now, I am having some problems with it because I perform two simultaneous http calls to IHP that again do external http API call and returns the data.

These two endpoints don't interact with the database except from that they both use `currentUser`.

```haskell
    action ListGithubOrganizationsAction = do
        case currentUser.githubAccessToken of
            Nothing ->
                error "Tried to list Github organizations, but user had no access token"
            Just accessToken -> do
                githubOrgs <- listGithubOrganizations accessToken
                renderJson githubOrgs

    action ListGithubUserReposAction =  do
        let user = currentUser
        case (user.githubLogin, user.githubAccessToken) of
            (Just githubUserName, Just accessToken) -> do
                let page = param @Int "page"
                userRepos <- listUserGithubRepos (ListGithubRepos {..})
                renderJson userRepos
            _ ->
                error "Missing github username or github access token"
```

It results in one of the calls are failing for seemingly no good reason because of this.

The error on `ListGithubOrganizationsAction` is following:

```haskell
EnhancedSqlError {sqlErrorQuery = "GRANT USAGE ON SCHEMA public TO ?", sqlErrorQueryParams = [EscapeIdentifier "ihp_authenticated"], sqlError = SqlError {sqlState = "XX000", sqlExecStatus = FatalError, sqlErrorMsg = "tuple concurrently updated", sqlErrorDetail = "", sqlErrorHint = ""}}
```

I saw a StackOverflow thread that seemed to shed some light on this: https://stackoverflow.com/questions/19382284/postgresql-error-tuple-concurrently-updated that it`s probably because of competing database transactions on same row.

Could this issue be fixable in IHP, or are there workarounds?

Edit: I fixed my own problem by performing the requests in a concecutive order, but still I guess this is generally a concurrency issue

**Comment by mpscholten** [comment] 2022-10-17 16:28
This is a kind of known issue (atleast known to me, it's also happend on thin.dev :D). The issue is the call to `ensureAuthenticatedRoleExists` in the FrontController.

My workaround so far was to delete that call from the FrontController. The sql commands triggered by `ensureAuthenticatedRoleExists` only have to be run once. Once the sql role/user for the RLS commands is set up, it doesn't actually need to be called anymore. So unless you reset your database, you can remove that function call (if you need to recreate the db, you can manually run the required SQL commands here https://github.com/digitallyinduced/ihp/blob/master/IHP/DataSync/Role.hs#L31)

**Comment by kodeFant** [comment] 2022-10-30 09:13
Thanks, that`s clarifying :)

**Comment by mpscholten** [comment] 2022-10-30 11:30
> Could it be solved without any manual queries by just running once in the main function in Main.hs for example? Or some other place where code only runs once on startup?

Yes, that's a good point 👍

**Comment by mpscholten** [comment] 2023-04-15 10:17
This should be fixed via https://github.com/digitallyinduced/ihp/pull/1642/commits/42cfacd36c0bf4d8abc21fa496410b9d61e9a83e 👍

**Closed** 2023-04-15 10:44 UTC
Labels: bug
